# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7b65f2b5ea411f9e3eda31e2d71e849eb65e9d2559cf941095cc9af5be8832ca9afd284c811e2b0457671595decdfa15c1e04838d4130940ac6a291ef0d1fc6

test:
  secret_key_base: 554e83909a975bd9ace299bc83f97e3acbe900806eae4ad1311aedde87fda624c981041efce09181a49b72bd1d1f132b5eae1f54adc6f4c6f047ae6771827f42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
